### PR TITLE
Parquet appending

### PR DESCRIPTION
**Pull request by yohplala**
Hi @bmoscon ,

This PR implements appending of parquet files, along with a `counter` that keeps track the number of times each parquet file is incremented.
This feature solves problem presented in #19 (albeit being not exactly the feature requested) and problem presented in #108.
This branch has been made over PR #105, so commit from from PR #105 is already in this PR.

**Implementation note 1**
There is one counter per  `exchange`/`data_type`/`pair` data for coping up with the case of scarcely updated data. In this case, the appending rate of each file is not necessarily the same (when there is no data for a `exchange`/`data_type`/`pair`, this specific data is not dumped into parquet file as per legacy implementation). Each parquet file follows then its own appending rate, so to say.
(I implemented this feature actually in 3 different versions this week-end, and earlier versions used a single counter for all files)

**Implementation note 2**
As indicated in config file, a not closed parquet file cannot be read. But a closed file cannot be appended efficiently: it needs to be read 1st and re-written and left open. Then new data can be appended.
So if cryptostore is stopped for any reason, last files are very likely unreadable (it requires to stop cryptostore at the last appending iteration when it is also closed).

If it seems to you required, I could implement in a new PR a new option to be activated by the user in the config file to enforce closing parquet file after each appending.
Reading and re-writing operations will certainly consume more CPU and memory however.

I decided not to retain this approach as a baseline, but to retain the most efficient way. Between each appending, file is left open, and only closed when the `appending_counter` is reached.

An alternative would be to run the closing task as soon as cryptostore exits. I do not know where to implement this actually?
If you give me a pointer and think it is appropriate, I can do that in a subsequent PR.

**Implementation note 3**
Well, I guess you already had this in mind, but if implementing multi-threading for data writing, please, keep [this line](https://github.com/yohplala/cryptostore/blob/69a734df828587a6a6df4266ca3c435cc0a07d2b/cryptostore/aggregator/aggregator.py#L83) out of the multi-threading stuff.

Bests

### CODE REVIEW

**Comment by bmoscon** [comment]
now that the other issue is resolved, let me take a look at this one :D

**Comment by yohplala** [comment]
Hello @bmoscon,
I am about to be done with the optimization of Redis.py.
I see this story of separator for google drive folder has kind of messed up my master (with commits not in legacy cryptostore, but still in my master).
I am about to scrap everything on my repo (including this parquet appending branch).
I have backed-up all file locally.
I will then re-create each branch separately from master branch.
So we can close this PR, I will re-issue it as soon as I have re-created a clean 'parquet_appending' branch.
(this evening I think)
Sorry for the disturbance.
Bests

**Comment by bmoscon** [comment]
@yohplala ok perfect, that will definitely make it easier to manage these things. Branching is the preferred approach!

**Comment by yohplala** [comment]
Cancelled / Being replaced by a clean PR

**Pull request closed without merging**
