### PR TITLE
Allow to configure endpoint to support third-party s3 compatible storage (e.g. Wasabi)

### PR DESCRIPTION
**Pull request by joelrich**
I have tested this change with
```endpoint: https://s3.eu-central-1.wasabisys.com```

### CODE REVIEW

**Comment by bmoscon** [comment]
I looked into the boto3 docs, the param listed there is `endpoint_url` so not sure why this differs?

**Comment by joelrich** [comment]
It uses endpoint_url in aws_write: `endpoint_url=endpoint `
I just kept it shorter because all other param names are shorter than the actual aws param names too. But sure, can rename it to endpoint_url if you want to. And no, I haven't tested it with Amazon S3.

**Comment by bmoscon** [comment]
@joelrich I'll test this today against AWS and if it works as-is, I'll merge it (to test I'd just leave the arg as None)

**Comment by bmoscon** [comment]
@joelrich tested against AWS - works as expected! Thanks for the PR

**Pull request merged**
