### PR TITLE
Overall changes to allow for wide_tables functionality

### PR DESCRIPTION
**Pull request by abstractconnections**
# wide_tables functionality for l2_book data (with book_depth) and Arctic 

1 - added **wide_tables** in config.yaml under "arctic:mongodb/.."

2 - added two checks in /data/storage.py, the first in the __init__ method
which raises an exception if **wide_tables** is enabled and Arctic is **not** one of the
storage mediums, the second check is on the **__init_helper** method and it
sets a True flag on Arctic if **wide_tables** is enabled.

3 - As a follow up on the previous one, I added an extra positional argument in
the __init__ method of /data/arctic.py to accept the True flag and be able to use the 
**wide_tables** functionality. (default is False), as well as an attribute **self.wide**.

4 - Modified /data/arctic.py write method to accommodate the new option of
**wide_tables**, which when enabled and data_type == L2_BOOK, it imports a function
**wide_book()** located in  /data/arctic_wt.py - This is where the dataframe
transformation happens.

5 - Modified /aggregator/aggregator.py loop method: Added a new positional argument
**wide_tables** to both Redis and Kafka instance calls as well as to /aggregator/redis.py
and /aggregator/kafka.py classes __init__ mehtods. (default is False, same as arctic).
The same attribute **self.wide** is used in both Redis and Kafka
classes to refer to the new argument **wide_tables** that the class now accepts.

6 - Modified /aggregator/redis.py read method:
For the **wide_tables** functionality to work you need to return a list of dictionaries, 
where each dictionary is an update from the exchange (a single timestamp) - you just 
return a list of the update messages without modifying such messages.
The **book_flatten()** function is then only called when **wide_tables** is **not** enabled.
The loop transformation from strings to floats is also unnecessary, since we know that
if we are using **wide_tables** we are storing a DataFrame to arctic, and so we can
vectorize this transformation on the DataFrame before writing to Arctic.

-- I don't have Kafka installed so I added (commented) the same functionality
-- to the Kafka class but I couldn't confirm that it works. If you can, please
-- confirm it, otherwise let me know and I will install Kafka.

7 - Added bits of documentation all around - mostly doc strings.

ps: In /data/arctic.py there's a print function to show the new **wide_tables** transformation - it's merely to show how the DataFrame will be stored and should be deleted.

### CODE REVIEW

**Comment by xiandong79** [comment]
Can parquet files have the same feature?

**Comment by xiandong79** [comment]
"wide_tables functionality" means that the number of columns of dataframe is the same as the current format, but the size of each unit/block is different? Due to some blocks may contain 3 orderbook updates, some blocks may only contain 1 orderbook updates?

I guess this meaning from book_flatten() function.

**Comment by abstractconnections** [comment]
> "wide_tables functionality" means that the number of columns of dataframe is the same as the current format, but the size of each unit/block is different? Due to some blocks may contain 3 orderbook updates, some blocks may only contain 1 orderbook updates?
> 
> I guess this meaning from book_flatten() function.

I am not sure I understand your last question. Basically "wide_tables" is just a different way to store the same data, which when used with arctic can bring a lot of benefits.
With "wide_tables" enabled each entry in Arctic corresponds to a single timestamp and each column either represents the price or the size at each level (each level comes in pairs of price/size).

The format is the following:
timestamp  |  'asks[0].price'  |  'asks[0].size'  |  'bids[0].price'  |  'bids[0].size'  |  'asks[N].price' | ...
timestamp  | ...   

From "ask[0].price" to "ask[N].price", the price increases, and from "bids[0].price" to "bids[N].price" the price decreases, so "asks[5].price" is the sixth lowest ask, and "bids[6].price" is the sixth highest offer and so on.

Now, imagine in the config_file you set "book_depth: 20", you will get 80 columns for each entry (each timestamp), 20 columns for ask[n].price, 20 columns for ask[n].size, 20 for  bids[n].price and 20 for bids[n],size.

What this allows you to do then is i.e run different backtests with different depth and only query the depth levels that you need. For a quick backtest you could call lib.read('l2_book-BTC-USD', columns=['asks[0].price', 'bids[0].price']), where you are only reading the top bid ask prices, this makes it much more efficient in memory and cpu because you are only querying two columns. Another time you could prefer to run a more in-depth backtest where you need to access all 20 levels depth book (assuming book_depth for this particular symbol is 20), and if so you could just call lib.read('l2_book-BTC-USD') and you get the 80 columns per timestamp. Choosing to store data with "wide_tables" enabled gives you this type of flexibility.

Let me know if you have further questions!

**Comment by bmoscon** [comment]
there are a number of issues here: https://app.codacy.com/app/bmoscon/cryptostore/pullRequest?prid=4034601

also, lots of indentation and quoting changes which will only muddy the change history

**Pull request closed without merging**
