### PR TITLE
WHALE_ALERT & COINGECKO new feeds

### PR DESCRIPTION
**Pull request by yohplala**
### Description of code

- [x] - Tested
- [x] - Changelog updated

Hi @bmoscon
This PR contains 3 main features & a bugfix:

- **1/** new feed `COINGECKO` coming with a new channel `profile`
- **2/** new feed `WHALE_ALERT` coming with a new channel `transactions` (on-chain transactions)
- **3/** because `WHALE_ALERT` connects to a REST API requiring an API key, I further implemented a 'path' for any 'unknown' parameter specified in `cryptostore` config file, within the `exchange` section, to be forwarded to the feed object that is created. An 'unknown' parameter is one that is not the name of a channel as specified in `cryptofeed/defines.py`, nor `retries`, nor `channel_timeouts`. This makes possible for Whale Alert feed to forward the API key and other required parameters to configure the feed as per user's pricing plan.
- 4/ I also integrated PR #130 directly in this PR

I am closing the other PR #136  that only contains CoinGecko feature and PR #130.
Bests,

### CODE REVIEW

**Comment by iamkucuk** [comment]
Is this still a thing? I'm very curious about collecting data from whale alert.

Btw, a humble suggestion: Don't just push all your updates in one PR. It makes it easier to track which PR changes what (especially for hunting bugs).

**Comment by yohplala** [comment]
Hi @bmoscon,
Ok for me as well for this PR. Please, share any feedbacks if you wish me to review some points. Thanks.

**Review by bmoscon — APPROVED** [review]

**Comment by bmoscon** [comment]
I think these changes are fine. Two things I'll want to do before this is merged. 1. Properly support authenticated feeds. Its close now with my recent changes to connections. 2. whale alert currently is broken. 

Neither of these changes should be major, should be a week or two at most before this will be good to go

**Comment by bmoscon** [comment]
@yohplala I'm ready to take this PR if you can resolve the last few conflicts - thanks and sorry its taken so long!

**Comment by yohplala** [comment]
Hi @bmoscon, ok, thanks. I will have a look during begining of week, and see to that. Bests

**Comment by yohplala** [comment]
> @yohplala I'm ready to take this PR if you can resolve the last few conflicts - thanks and sorry its taken so long!

Hi @bmoscon, a quick word to say that I love what you did in cryptofeed/coingecko, this is great.
Up to now I could not take the time to review these changes you made.
Before updating this PR, I need to make sure the feeds COINGECKO and WHALE_ALERT are operational in last cryptofeed version.
This evening, I only checked COINGECKO.
Tomorrow, I should be able to inspect WHALE_ALERT.
Thanks again @bmoscon!

**Comment by bmoscon** [comment]
I dont think whale alert is. The things like keys and secrets come via the config file now, so you'd need to change the code to get them from self.config.whale_alert.key_id, etc

**Comment by yohplala** [comment]
Hi @bmoscon 

A short notice to tell you that I have not forgotten the topic.
I am sure you are aware of it, but other potentially interested users may wonder about the time needed for htis PR.
At the moment, I am in stand-by on this.

Situation is that due to the recent changes in websocket/http request management in cryptofeed, there is not yet example of code with  **dynamic http requests** in cryptofeed, which is what is needed for WHALE_ALERT.
Indeed, in WHALE_ALERT, 2 parameters have to be set at each new http request (`cursor` and `start_time`).

2 things are currently pending:
- in [ticket 401](https://github.com/bmoscon/cryptofeed/issues/401), I asked to @bmoscon what is the correct way to manage **dynamic http request** in the new cryptofeed logic?
- in the very same ticket, @olibre indicated he has already started to work out something to handle this, and is preparing a PR for review.

At the moment, I am 'waiting' either one or the other (being busied on other topics, this is completely fine for me).

**Comment by bmoscon** [comment]
yep - i think we're both waiting :)

**Comment by bmoscon** [comment]
@yohplala can you fix the conflicts and remove the parts for Whale alert, and then I'll merge this?

**Comment by yohplala** [comment]
> @yohplala can you fix the conflicts and remove the parts for Whale alert, and then I'll merge this?

Hi @bmoscon 
Ok will do.  Bryant, do you want to keep the ability to forward parameters to feed?
I implemented this in this PR : any parameter that is read in the config file and cryptostore does not know is forwarded to the feed.
I used this to forward specific parameters to WHALE_ALERT and related to the caracteristics of the plan the user has (the number of requests the user can do, the history the user has access to, and also to manage the authentication).

Even if you removed WHALE_ALERT from cryptofeed, you may want to keep this feature.
What would you prefer here?

**Comment by yohplala** [comment]
You can see this here. Cryptostore does not know about `sleep_time`, `max_history`... so it forwards them to WHALE_ALERT feed.
This feature is generic, I implemented it for WHALE_ALERT, but it would work the same for any feed.

Capture d’écran de 2021-05-05 07-06-42

**Comment by yohplala** [comment]
Closing this PR in profit to PR #184.

**Pull request closed without merging**
