### PR TITLE
Fix the unclear parquet name in S3.

### PR DESCRIPTION
**Pull request by xiandong79**
Update on #81 
Thanks. @bmoscon

### CODE REVIEW

**Comment by chazzmoney** [comment]
This seems redundant/arbitrary. I'm not sure in which programmatic context you wouldn't have access to the filepath but do have access to the filename.

**Comment by xiandong79** [comment]
@chazzmoney  go to S3 webpage, and download the file directly. 
see the snapshot on #81

**Comment by chazzmoney** [comment]
In that context, the directory is at the top of the page.

snapshot

**Comment by xiandong79** [comment]
@chazzmoney if the user only downloads one file by click to his Local Desktop. !!!

Then, the user only gets a file named 1587845245.parquet !!!!!

the user will lose mind which coin, which exchange it is !!!!

close the issue if you want !!!

**Comment by chazzmoney** [comment]
I’m not an admin,  just another user. I can’t close anything.

I understand your challenge now.

However, I think I have a better solution for you still. Downloading parquet files one by one seems tedious, especially if you want to view the data in all of them combined.

Instead, can you use the aws cli to download the entire directory structure to your local machine?

https://stackoverflow.com/questions/8659382/downloading-an-entire-s3-bucket

This is very fast and ensures you have a one line command to run to download any files you don’t have locally. It will also create the same directory structure on your local machine, so you will get the context too.

Would that help you?

**Pull request merged**
